name: terraform config

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform-test:
    name: terraform 
    runs-on: ubuntu-latest
    steps:
    - name: checking repo
      uses: actions/checkout@v2

    - name: setting up terraform 
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.7"

    - name: AWs setup
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform init 
      run: terraform init

    - name: Terraform plan
      run: terraform apply auto-approve
